### ISSUE TITLE
[Anon] Vampire Counts: Accursed Armor Hidden on Cavalry 

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/Warhammer-The-Old-World#101] opened 2024-11-11 07:01 UTC
**Problem:**
Accursed Armor Hidden on Cavalry 

**Expected:**
Accursed Armor is available to infantry and Cavalry 

**List:** https://www.newrecruit.eu/app/list/STiDj
**Unit:** Vampire Thrall, id: a906e64d-80532883

**Comment by Tidomann** [comment] 2024-11-11 19:26
Previously fixed in Commit c9704b3

Unable to reproduce with
Revision: 51
GameSystem revision: 126
Libraries: Magic Items: 107, The Lores of Magic: 37, Mercenaries: 14

**Closed by Tidomann** 2024-11-11 19:26 UTC
